# Generated by Django 5.2.10 on 2026-01-27 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylog',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
