# Generated by Django 5.2.10 on 2026-01-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='task_files/'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
