# Generated by Django 5.2.10 on 2026-01-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskcomment_file_alter_taskcomment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='manager_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('APPROVED', 'Approved')], default='PENDING', max_length=20),
        ),
    ]
